### ISSUE TITLE
Prototype v0.1 bugs

### ISSUE THREAD

**Issue by David-Estevez** [UC3Music/Shiva#1]
Things to correct in version 1.0 / 0.2:
- [x] Pads for through-hole components are too thin.
- [x] Reposition Teensy board (USB and MIDI connector collide).
- [x] Jack connectors are placed in the wrong side of the board.

Critical:
- [x] Silkscreens for R12 and R8 are swapped (reported by @JorFru )

**Comment by David-Estevez** [comment]
* [x] Op-amp inputs are swapped for all channels (reported by @SerjSanchez)

**Comment by David-Estevez** [comment]
@SerjSanchez was right, the + and - inputs of the op-amps were swapped, and therefore it was working in an unstable configuration (due to positive feedback).

Changing this in the PCB (+other hacks) makes it work properly, although it might need a gain higher than 1. But the gain could be adjusted with the correct circuit by adding resistors.

**Comment by David-Estevez** [comment]
Fixed flipped jacks, swapped op-amp channels, thin pads, swapped silkscreen ids (f301a64)

**Comment by David-Estevez** [comment]
Components placement fixed at 8a9add0

**Comment by JorFru** [comment]
Pick logo and UC3Music name logo are outdated versions.
Updated versions will be available soon [here](https://github.com/UC3Music/uc3music-logos/tree/master/logos)

**Comment by David-Estevez** [comment]
Issue #13 already covers that issue
